version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/java:0-17
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
  mq:
    image: icr.io/ibm-messaging/mq:latest
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: LPQAINT
    ports:
      - "1431:1414"
      - "9443:9443"
